---
title: "Good 2024 'Power Over Presence: Women’s Representation in Comprehensive Peace Negotiations and Gender Provision Outcomes' Reproduction"
author: "Nina Rice & Erika Garza-Elorduy"
format: pdf
editor: visual
---

```{r}
repdata <- read.csv("~/Downloads/dataverse_files/PADD_Agreement Level.csv")
```

```{r}
library(ggplot2)

# Calculate frequencies as a percentage of the total
table_freq <- prop.table(table(repdata$GeWom)) * 100


freq_data <- as.data.frame(table_freq)
names(freq_data) <- c("GeWom", "Frequency")


ggplot(freq_data, aes(x = GeWom, y = Frequency, fill = GeWom)) +
  geom_bar(stat = "identity", width = 0.7) +  
  labs(x = "Provisions for Women", y = "Frequency (%)", title = "Histogram of Provisions for Women") +
  scale_x_discrete(limits = c("0", "1"), labels = c("0" = "No Provisions", "1" = "Provisions")) +
  theme_minimal() +
  theme(axis.title = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 10),
        plot.title = element_text(size = 14, face = "bold", hjust = 0.5))
```

```{r}
library(corrplot)
library(tidyverse)

DV <- "GeWom"
IVs <- c("FemSig_P", "FemNeg_P", "FemMed_P", "FemOb_P")
 
repdata <- repdata %>%
  mutate(across(all_of(c(DV, IVs)), as.numeric))
 
cor_matrix <- cor(repdata %>% select(all_of(c(DV, IVs))), use = "pairwise.complete.obs")
 
corrplot(cor_matrix, method = "color", type = "lower",
         col = colorRampPalette(c("lightblue", "blue", "darkblue"))(200),
         tl.col = "black", tl.cex = 0.8)
```

```{r}
library(naniar)
vis_miss(repdata) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 3))
```
